import { Video } from './video';
import { User } from './user';

/
 * Represents an AI technology application for video creation.
 * This application, named "VidNexus," focuses on generating AI-driven videos.
 * The brand "AI" reflects cutting-edge technology and modern design principles.
 * 
 * @module types
 */

/
 * Interface representing a video project.
 */
export interface VideoProject {
    id: string; // Unique identifier for the video project
    title: string; // Title of the video project
    description: string; // Description of the video project
    createdBy: User; // User who created the video project
    createdAt: Date; // Date when the project was created
    updatedAt: Date; // Date when the project was last updated
    status: ProjectStatus; // Current status of the video project
    video: Video; // Associated video data
}

/
 * Enum representing the possible statuses of a video project.
 */
export enum ProjectStatus {
    DRAFT = 'draft', // The project is in draft state
    PUBLISHED = 'published', // The project has been published
    ARCHIVED = 'archived' // The project is archived
}

/
 * Interface representing user information in the VidNexus application.
 */
export interface User {
    id: string; // Unique identifier for the user
    username: string; // Username of the user
    email: string; // Email address of the user
    createdAt: Date; // Date when the user registered
    lastLogin: Date; // Date of the user's last login
}

/
 * Interface representing a video generated by the AI technology.
 */
export interface Video {
    id: string; // Unique identifier for the video
    title: string; // Title of the video
    duration: number; // Duration of the video in seconds
    resolution: string; // Resolution of the video (e.g., '1080p', '4K')
    format: string; // Video format (e.g., 'mp4', 'mov')
    createdAt: Date; // Date when the video was created
    transcribed: boolean; // Indicates if the video has been transcribed
}

/
 * Function to create a new video project.
 * 
 * @param title - The title of the video project.
 * @param description - The description of the video project.
 * @param user - The user creating the project.
 * @returns A new VideoProject object.
 */
export function createVideoProject(title: string, description: string, user: User): VideoProject {
    const now = new Date();
    return {
        id: generateUniqueId(),
        title,
        description,
        createdBy: user,
        createdAt: now,
        updatedAt: now,
        status: ProjectStatus.DRAFT,
        video: {
            id: generateUniqueId(),
            title: ${title} Video,
            duration: 0,
            resolution: '1080p',
            format: 'mp4',
            createdAt: now,
            transcribed: false,
        }
    };
}

/
 * Generates a unique identifier for projects and videos.
 * 
 * @returns A unique identifier as a string.
 */
function generateUniqueId(): string {
    return 'id-' + Math.random().toString(36).substr(2, 9);
}